### ISSUE TITLE
Insertion of security headers in responses

### ISSUE THREAD

**Issue by jonatanhal** [Doctor-love/certainly#1]
looking at the [ReverseProxy](https://golang.org/pkg/net/http/httputil/#ReverseProxy) type, 
it should be pretty simple to add various headers; as illustrated in the following pseudo-go.

```
func modifier(r *http.Response) (err error) {
	err = nil // this might be redundant
	http.Response.Header.Add("Strict-Transport-Security","max-age=31536000")
}
func main() {
	rp := NewSingleHostReverseProxy(foo)
	rp.ModifyResponse = modifier
}
```

Secure cookies need some basic parsing, looping over each cookie and adding the keyword.

**Comment by Doctor-love** [comment]
I suspected so - go'sh the standard library is nice!

**Comment by Doctor-love** [comment]
Fixed!
